#!/usr/bin/env bash
# OPTIONAL — bring up a self-hosted morphik-core so the document tools hit a
# real backend. Not needed to validate the auth layer: run-all.sh proves the
# whole integration without it, and verify.sh self-skips the document checks.
#
#     bash authplane-test/backend-up.sh
#
# WARNING: this clones morphik-core and builds a ~10 GB image (Python + ML
# deps). Expect 20-40 minutes on a first run and plenty of free disk.
#
# It applies three fixes found while running it, all in a generated override
# file so morphik-core's own tree is left untouched:
#
#   1. Its docker-compose.yml mounts ./morphik.toml, the HOST config, whose
#      [redis] block points at localhost:6379. Inside the container that is the
#      container itself, so the service dies with "Redis not reachable after
#      20s". morphik.docker.toml is the variant with redis://redis:6379/0.
#   2. ColPali is disabled. It downloads a multi-GB vision model at startup and
#      is irrelevant to auth testing.
#   3. bypass_auth_mode = true. morphik-core requires its own JWT, and
#      morphik-mcp cannot supply one to a local HTTP backend: the morphik://
#      URI form hardcodes https:// (src/core/config.ts). That is Morphik's
#      inbound auth, a separate layer from the one this integration adds.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
CORE="$(cd "$HERE/../.." && pwd)/morphik-core"

command -v docker >/dev/null 2>&1 || { echo "docker is required" >&2; exit 1; }
docker info >/dev/null 2>&1 || { echo "the Docker daemon is not reachable" >&2; exit 1; }

if [ ! -d "$CORE" ]; then
  echo "==> cloning morphik-core into $CORE"
  git clone --depth 1 https://github.com/morphik-org/morphik-core.git "$CORE"
fi
cd "$CORE"

[ -f .env ] || { printf 'JWT_SECRET_KEY=%s\n' "$(openssl rand -hex 32)" > .env; echo "==> generated .env"; }

echo "==> writing morphik.authplane-test.toml (colpali off, dev auth bypass)"
cp morphik.docker.toml morphik.authplane-test.toml
sed -i 's/^enable_colpali = true/enable_colpali = false/;
        s/^colpali_mode = "local"/colpali_mode = "off"/;
        s/^bypass_auth_mode = false/bypass_auth_mode = true/' morphik.authplane-test.toml

echo "==> writing docker-compose.override.yml"
cat > docker-compose.override.yml <<'YAML'
# Generated by morphik-mcp/authplane-test/backend-up.sh. See that script for why.
services:
  morphik:
    command: uv run start_server.py --skip-redis-check --skip-ollama-check
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./morphik.authplane-test.toml:/app/morphik.toml
      - huggingface_cache:/root/.cache/huggingface
      - ./core:/app/core
YAML

echo "==> starting postgres + redis"
docker compose up -d postgres redis

echo "==> building morphik (slow on first run)"
docker compose build morphik

echo "==> starting morphik"
docker compose up -d morphik

echo -n "==> waiting for the API on :8000 "
for _ in $(seq 1 90); do
  if curl -fsS -o /dev/null http://localhost:8000/health 2>/dev/null; then
    echo " ready"
    curl -sS http://localhost:8000/health | python -m json.tool
    echo
    echo "Now re-run: bash $HERE/verify.sh   (tests 9-11 will no longer skip)"
    exit 0
  fi
  docker compose ps --format '{{.Service}} {{.Status}}' | grep -q "^morphik Up" || {
    echo; echo "ERROR: the morphik container exited. Last lines:" >&2
    docker compose logs morphik --tail 20 >&2; exit 1; }
  echo -n "."; sleep 10
done
echo
echo "ERROR: the API did not come up in time. Check: docker compose logs morphik" >&2
exit 1
